full_questions = {
'StartDate': 'StartDate',
'EndDate': 'EndDate',
'Status': 'Status',
'IPAddress': 'IPAddress',
'Progress': 'Progress',
'Duration in seconds': 'Duration in seconds',
'Finished': 'Finished',
'RecordedDate': 'RecordedDate',
'ResponseId': 'ResponseId',
'RecipientLastName': 'RecipientLastName',
'RecipientFirstName': 'RecipientFirstName',
'RecipientEmail': 'RecipientEmail',
'ExternalReference': 'ExternalReference',
'LocationLatitude': 'LocationLatitude',
'LocationLongitude': 'LocationLongitude',
'DistributionChannel': 'DistributionChannel',
'UserLanguage': 'UserLanguage',
'Q161': 'Please choose a title or identifier for your case study. This field is the unique identifier of the case study for the platform.',
'Q166': 'Please provide the physical address for the case study or description of location.',
'Q163': 'Which is the city and/or region is your case study is located in?',
'Q164': 'Which country is your case study located in?',
'Q167': 'Select which of the following best describes your case study in terms of spatial scope.',
'Q167_15_TEXT': 'Select which of the following best describes your case study in terms of spatial scope. Other',
'Q168': 'What is the approximate gross floor area GFA of your case study in square meters  all spaces and buildings?',
'Q242': 'At what phase is your case study currently in?',
'Q153': 'What is the age of the case study buildings? You can select more than one if you have multiple buildings.',
'Q233': 'Which of the following descriptors can be applied to your case study? You can select more than one if you have multiple buildings.',
'Q233_4_TEXT': 'Which of the following descriptors can be applied to your case study? You can select more than one if you have multiple buildings. Other',
'Q155': 'Building uses Select all that apply for your buildings. Please indicate other and fill in a use type if yours is missing from this list.',
'Q155_12_TEXT': 'Building uses Select all that apply for your buildings. Please indicate other and fill in a use type if yours is missing from this list. Other',
'Q248': 'If your case study included data collection from specific occupants: how many participants did you have?',
'Q239': 'Did your case study have an ethics review process IRB: etc.?',
'Q239_7_TEXT': 'Did your case study have an ethics review process IRB: etc.? Other',
'Q169': 'Has there been a publications about this case study? If so: provide the DOI or other link.',
'Q143_Id': "If you'd like: please upload any relevant reports and/or publications documenting the case study that might not available online. If there are multiple files: please upload a .zip file with all included. - Id",
'Q143_Name': "If you'd like: please upload any relevant reports and/or publications documenting the case study that might not available online. If there are multiple files: please upload a .zip file with all included. - Name",
'Q143_Size': "If you'd like: please upload any relevant reports and/or publications documenting the case study that might not available online. If there are multiple files: please upload a .zip file with all included. - Size",
'Q143_Type': "If you'd like: please upload any relevant reports and/or publications documenting the case study that might not available online. If there are multiple files: please upload a .zip file with all included. - Type",
'QID22': 'Does your case study include any of the following categories of analysis? Select all that apply For each of these categories that you select: you will be asked to specify details in a series of upcoming questions.',
'Q93': 'What types of occupants are included in the case study? Select all that apply',
'Q93_11_TEXT': 'What types of occupants are included in the case study? select all that apply - Other',
'Q98_1': "Please estimate the percentage distribution of the gender groups in your study adds up to 100%. If unknown put 'undefined' to 100%: - Female",
'Q98_2': "Please estimate the percentage distribution of the gender groups in your study adds up to 100%. If unknown put 'undefined' to 100%: - Male",
'Q98_3': "Please estimate the percentage distribution of the gender groups in your study adds up to 100%. If unknown put 'undefined' to 100%: - Diverse",
'Q98_12': "Please estimate the percentage distribution of the gender groups in your study adds up to 100%. If unknown put 'undefined' to 100%: - Undefined",
'Q197_1': "Please estimate the percentage distribution of the age groups in your study adds up to 100%. If unknown put 'undefined' to 100%: - Children and teenagers ~ <19 years",
'Q197_2': "Please estimate the percentage distribution of the age groups in your study adds up to 100%. If unknown put 'undefined' to 100%: - Adults ~19-65 years",
'Q197_12': "Please estimate the percentage distribution of the age groups in your study adds up to 100%. If unknown put 'undefined' to 100%: - Older adults ~65+ years",
'Q197_13': "Please estimate the percentage distribution of the age groups in your study adds up to 100%. If unknown put 'undefined' to 100%: - Undefined",
'Q197_14': "Please estimate the percentage distribution of the age groups in your study adds up to 100%. If unknown put 'undefined' to 100%: - Different age brackets used: please describe",
'Q197_14_TEXT': "Please estimate the percentage distribution of the age groups in your study adds up to 100%. If unknown put 'undefined' to 100%: - Different age brackets used: please describe - Text",
'Q99_1': 'Please estimate the percentage distribution of the education level of the participants in your study - No formal degree',
'Q99_2': 'Please estimate the percentage distribution of the education level of the participants in your study - High School',
'Q99_6': 'Please estimate the percentage distribution of the education level of the participants in your study - Technical Training',
'Q99_3': 'Please estimate the percentage distribution of the education level of the participants in your study - 2-year college / Bachelor Degree',
'Q99_4': 'Please estimate the percentage distribution of the education level of the participants in your study - 4-year college / Master degree',
'Q99_5': 'Please estimate the percentage distribution of the education level of the participants in your study - PhD',
'Q99_7': 'Please estimate the percentage distribution of the education level of the participants in your study - Post graduate studies',
'Q99_8': 'Please estimate the percentage distribution of the education level of the participants in your study - Undefined',
'Q100_1': "Please estimate the percentage distribution of the income level of the participants in your study. If unknown put 'undefined' to 100%: - Low income",
'Q100_2': "Please estimate the percentage distribution of the income level of the participants in your study. If unknown put 'undefined' to 100%: - Medium income",
'Q100_3': "Please estimate the percentage distribution of the income level of the participants in your study. If unknown put 'undefined' to 100%: - High income",
'Q100_4': "Please estimate the percentage distribution of the income level of the participants in your study. If unknown put 'undefined' to 100%: - Undefined",
'Q219_1': "Please estimate the level of health /  well-being of the participants at the time of your study. If unknown put 'undefined' to 100%: - No known physical illness: disease or mental distress",
'Q219_2': "Please estimate the level of health /  well-being of the participants at the time of your study. If unknown put 'undefined' to 100%: - Participants experiencing physical illness: disease or mental distress please specify",
'Q219_2_TEXT': "Please estimate the level of health /  well-being of the participants at the time of your study. If unknown put 'undefined' to 100%: - Participants experiencing physical illness: disease or mental distress please specify - Text",
'Q219_3': "Please estimate the level of health /  well-being of the participants at the time of your study. If unknown put 'undefined' to 100%: - Undefined",
'Q16_1': 'Which data was collected and how? - Data Not Collected',
'Q16_2': 'Which data was collected and how? - Interview',
'Q16_3': 'Which data was collected and how? - Survey',
'Q16_4': 'Which data was collected and how? - Smart Phone',
'Q16_5': 'Which data was collected and how? - Smart Watch',
'Q16_6': 'Which data was collected and how? - Personnel file',
'Q16_7': 'Which data was collected and how? - Statistical data set I.e. census data',
'Q16_8': 'Which data was collected and how? - Observation by researchers',
'Q16_9': 'Which data was collected and how? - Other please specify in the next question',
'Q17': 'Please use the space below to leave other details about the occupants that have not been requested from previous questions that are important to your case study.',
'Q45': 'Which is the title of the typical person who manages and operates the building?',
'Q45_7_TEXT': 'Which is the title of the typical person who manages and operates the building? Other',
'Q46': 'What is the best description of the entity that employs the operations personnel for your case study?',
'Q46_7_TEXT': 'What is the best description of the entity that employs the operations personnel for your case study? Other',
'Q47': 'How often do  operations personnel physically occupy the case study building?',
'Q47_3_TEXT': 'How often do  operations personnel physically occupy the case study building? Other',
'Q49': 'Does the administration of the building or the operators expressively declare the goals driving their operational decisions?',
'Q49_11_TEXT': 'Does the administration of the building or the operators expressively declare the goals driving their operational decisions? Other',
'Q50': "For which of the following energy-relevant interfaces operators restricted/blocked/locked occupants' operability?",
'Q50_5_TEXT': "For which of the following energy-relevant interfaces operators restricted/blocked/locked occupants' operability? Other",
'Q59': 'Were the operators surveyed about the challenges of their work?',
'Q60': "If yes: which of the following non-technical e.g.  interpersonal: organizational challenges in improving the building's energy efficiency was revealed?",
'Q60_5_TEXT': "If yes: which of the following non-technical e.g.  interpersonal: organizational challenges in improving the building's energy efficiency was revealed? Other",
'Q157': 'Does the building have a fully-programmable building automation system for HVAC controls? e.g.: a BACnet controls network for a commercial building or a smart thermostat for a residential building',
'Q158': 'Select the closest zone/room-level mechanical HVAC cooling configurations from the list can select multiple:NoteVAV: variable air volumeCAV: constant air volumeAHU: air handling unitDOAS: dedicated outdoor air systemVRF: variable refrigerant flow',
'Q158_13_TEXT': 'Select the closest zone/room-level mechanical HVAC cooling configurations from the list can select multiple:NoteVAV: variable air volumeCAV: constant air volumeAHU: air handling unitDOAS: dedicated outdoor air systemVRF: variable refrigerant flow - Other',
'Q176': 'Which of the following better describes the ventilation in your case study building?',
'Q176_7_TEXT': 'Which of the following better describes the ventilation in your case study building? - Other',
'Q177': 'How many HVAC zones do you have in your case study? if you studied only a fraction of the zones in the building: just respond for the number of zones that you studied',
'Q178': 'Approximate size per floor area and per seats assigned of your typical HVAC zone in the case study. A zone implies to a space with a dedicated terminal device e.g.: a VAV terminal.',
'Q189': 'Please indicate the approximate number of occupants for a typical HVAC zone in your case study.',
'Q179': 'Select the zone sensors used for the control of the HVAC',
'Q179_9_TEXT': 'Select the zone sensors used for the control of the HVAC - Other',
'Q232': 'What is the age of your HVAC control system?',
'Q233': 'Which of the following best describes the type of luminaires in your case study building?',
'Q233_9_TEXT': 'Which of the following best describes the type of luminaires in your case study building? - Fluorescent bulb size T5/ T8/ T12',
'Q233_5_TEXT': 'Which of the following best describes the type of luminaires in your case study building? - Other',
'Q234': 'Which of the following best describes the lighting control systems in your case study?',
'Q235': 'Select the types of sensors available for lighting controls prior to your study.',
'Q235_3_TEXT': 'Select the types of sensors available for lighting controls prior to your study. - Other',
'Q236': 'Approximate size per floor area and per seats assigned of your typical Lighting zone in the case study. A zone implies to a space in which all luminaires are turned on/off concurrently.',
'Q237': 'Please indicate the approximate number of occupants for a typical Lighting zone in your case study.',
'Q238': 'Select list of building components/systems controllable by occupants',
'Q238_6_TEXT': 'Select list of building components/systems controllable by occupants - Other',
'Q21_1': 'What kind of occupancy data was collected in this case study and what kinds of methods are used for this? - Binary presence/absence at the building/system level',
'Q21_2': 'What kind of occupancy data was collected in this case study and what kinds of methods are used for this? - Binary presence/absence at the zone/room level',
'Q21_3': 'What kind of occupancy data was collected in this case study and what kinds of methods are used for this? - People count at the building/system level',
'Q21_4': 'What kind of occupancy data was collected in this case study and what kinds of methods are used for this? - People count at the zone/room level',
'Q21_5': 'What kind of occupancy data was collected in this case study and what kinds of methods are used for this? - Occupant activity at the building/system level',
'Q21_6': 'What kind of occupancy data was collected in this case study and what kinds of methods are used for this? - Occupant activity at the zone/room level',
'Q21_7': 'What kind of occupancy data was collected in this case study and what kinds of methods are used for this? - Other',
'Q21_7_TEXT': 'What kind of occupancy data was collected in this case study and what kinds of methods are used for this? - Other',
'Q23': 'What image-based methods  are used?',
'Q23_3_TEXT': 'What image-based methods  are used? Other',
'Q25': 'What mechanical sensing methods are used?',
'Q25_4_TEXT': 'What mechanical sensing methods are used? Other',
'Q27': 'What motion sensing methods are used?',
'Q27_5_TEXT': 'What motion sensing methods are used? Other',
'Q29': 'What radio-based methods are used?',
'Q29_6_TEXT': 'What radio-based methods are used? Other',
'Q31': 'What environmental sensing methods are used?',
'Q31_8_TEXT': 'What environmental sensing methods are used? Other',
'Q33': 'What building equipment states are examined?',
'Q33_7_TEXT': 'What building equipment states are examined? Other',
'Q36': 'What building equipment interactions are examined?',
'Q36_7_TEXT': 'What building equipment interactions are examined? Other',
'Q39': 'What smart devices are used?',
'Q39_4_TEXT': 'What smart devices are used? Other',
'Q41': 'What consumption sensing methods are used?',
'Q41_5_TEXT': 'What consumption sensing methods are used? Other',
'Q43': 'What kind of human-in-the-loop methods are used?',
'Q43_5_TEXT': 'What kind of human-in-the-loop methods are used? Other',
'Q238_1': 'Which data was collected in this case study using which methods of human-building interfaces? - Data Not Collected',
'Q238_2': 'Which data was collected in this case study using which methods of human-building interfaces? - Interview',
'Q238_3': 'Which data was collected in this case study using which methods of human-building interfaces? - Survey',
'Q238_4': 'Which data was collected in this case study using which methods of human-building interfaces? - Smart Phone',
'Q238_5': 'Which data was collected in this case study using which methods of human-building interfaces? - Smart Watch',
'Q238_6': 'Which data was collected in this case study using which methods of human-building interfaces? - Statistical data set I.e. census data',
'Q238_7': 'Which data was collected in this case study using which methods of human-building interfaces? - Observation by researchers',
'Q238_8': 'Which data was collected in this case study using which methods of human-building interfaces? - Other please specify in the next question',
'Q103': 'Please indicate all interaction interfaces between user and building considered in the study:',
'Q103_9_TEXT': 'Please indicate all interaction interfaces between user and building considered in the study: - Other',
'Q105_1': 'Please select the appropriate characteristic of the each interface: - Manual control',
'Q105_2': 'Please select the appropriate characteristic of the each interface: - Automated control',
'Q105_3': 'Please select the appropriate characteristic of the each interface: - Individual remote control phone: desktop: ...',
'Q105_4': 'Please select the appropriate characteristic of the each interface: - Control centrally for room',
'Q105_5': 'Please select the appropriate characteristic of the each interface: - Control centrally for building',
'Q105_6': 'Please select the appropriate characteristic of the each interface: - Other',
'Q105_6_TEXT': 'Please select the appropriate characteristic of the each interface: - Other - Text',
'Q105_7': 'Please select the appropriate characteristic of the each interface: - Not included',
'Q107': 'Please indicate all possible communication options of user with the operators? The question refers to non-residential buildings or building complexes with operators.',
'Q107_7_TEXT': 'Please indicate all possible communication options of user with the operators? The question reffers to non-residential buildings or building complexes with operators. Other',
'Q110': 'Were individual occupant experiences and motivations investigated?',
'Q111_1': 'Which individual occupant experiences and motivations were investigated and how were they collected? - Feelings / Emotions',
'Q111_2': 'Which individual occupant experiences and motivations were investigated and how were they collected? - Individual action logic',
'Q111_3': 'Which individual occupant experiences and motivations were investigated and how were they collected? - Attitude',
'Q111_4': 'Which individual occupant experiences and motivations were investigated and how were they collected? - Personal values',
'Q111_5': 'Which individual occupant experiences and motivations were investigated and how were they collected? - Beliefs',
'Q111_6': 'Which individual occupant experiences and motivations were investigated and how were they collected? - Lifestyle',
'Q111_7': 'Which individual occupant experiences and motivations were investigated and how were they collected? - Subjective norm',
'Q111_8': 'Which individual occupant experiences and motivations were investigated and how were they collected? - Cognitive factors',
'Q111_9': 'Which individual occupant experiences and motivations were investigated and how were they collected? - Biological factors',
'Q111_10': 'Which individual occupant experiences and motivations were investigated and how were they collected? - Level of education',
'Q111_11': 'Which individual occupant experiences and motivations were investigated and how were they collected? - Age',
'Q111_12': 'Which individual occupant experiences and motivations were investigated and how were they collected? Other',
'Q111_12_TEXT': 'Which individual occupant experiences and motivations were investigated and how were they collected? Other',
'Q113': 'Were socio-cultural context parameters investigated?',
'Q115_1': 'Which socio-cultural context parameters were investigated and how were they collected? - Social norms',
'Q115_2': 'Which socio-cultural context parameters were investigated and how were they collected? - Social values',
'Q115_3': 'Which socio-cultural context parameters were investigated and how were they collected? - Group dynamics',
'Q115_4': 'Which socio-cultural context parameters were investigated and how were they collected? - Peer education',
'Q115_5': 'Which socio-cultural context parameters were investigated and how were they collected? - Organisational norms',
'Q115_6': 'Which socio-cultural context parameters were investigated and how were they collected? - Cultural norms',
'Q115_7': 'Which socio-cultural context parameters were investigated and how were they collected? - Cultural values',
'Q115_8': 'Which socio-cultural context parameters were investigated and how were they collected? - Other',
'Q115_8_TEXT': 'Which socio-cultural context parameters were investigated and how were they collected? Other',
'Q152': 'Select the types of intervention included in the study. For each item you select: there will be a subsection enabled for further questions.',
'Q152_8_TEXT': 'Select the types of intervention included in the study. For each item you select: there will be a subsection enabled for further questions. Other',
'Q226_1_1': "What was the study timeframe? An educated guess is ok. If you don't know or the question is not applicable: indicate this. - Pre intervention period - Start date",
'Q226_1_2': "What was the study timeframe? An educated guess is ok. If you don't know or the question is not applicable: indicate this. - Pre intervention period - End date",
'Q226_2_1': "What was the study timeframe? An educated guess is ok. If you don't know or the question is not applicable: indicate this. - Intervention period - Start date",
'Q226_2_2': "What was the study timeframe? An educated guess is ok. If you don't know or the question is not applicable: indicate this. - Intervention period - End date",
'Q226_3_TEXT': "What was the study timeframe? An educated guess is ok. If you don't know or the question is not applicable: indicate this. Other",
'Q226_3_1': "What was the study timeframe? An educated guess is ok. If you don't know or the question is not applicable: indicate this. - Other - Start date",
'Q226_3_2': "What was the study timeframe? An educated guess is ok. If you don't know or the question is not applicable: indicate this. - Other - End date",
'Q137': 'What were the modes of control of the case study?',
'Q91': 'What was the knowledge of occupant regarding the intervention?',
'Q116': 'Who is the responsible for changes in controls or systems?',
'Q66': 'If automated: which type of actuation is part of the intervention?',
'Q111_1': 'What is the controlled parameter being modulated in the intervention? - Building component',
'Q69': 'Please specify "other" controlled parameter',
'Q231': 'How is this parameter changed at the zone level?',
'Q68_1': 'What is the controlled parameter being modulated in the intervention? - Setpoint change',
'Q70': 'Please specify "other" setpoint change that is being modulated',
'Q71': 'Schedule change occupant changes the setpoint',
'Q71_4_TEXT': 'Schedule change occupant changes the setpoint - Other',
'Q72': 'What was being direct actuated? occupant directly overrides the actuator state',
'Q72_4_TEXT': 'What was being direct actuated? occupant directly overrides the actuator state - Other',
'Q74': 'What control algorithm was used for the automated actuation as part of the intervention?',
'Q74_11_TEXT': 'What control algorithm was used for the automated actuation as part of the intervention? - Other',
'Q77_1': 'What is the controlled parameter being modulated in the intervention at the system level? - Building system',
'Q78': 'Please specify "other" controlled parameter',
'Q230': 'How is this parameter changed?',
'Q80_1': 'What is the controlled parameter being modulated in the intervention? - Setpoint change',
'Q84': 'Please specify "other"',
'Q81': 'What type of schedule change was implemented?',
'Q81_4_TEXT': 'What type of schedule change was implemented? Other',
'Q82': 'What system was direct actuation applied to?',
'Q82_4_TEXT': 'What system was direct actuation applied to? Other',
'Q83': 'What control algorithm was used in the actuation system intervention at the system level?',
'Q83_9_TEXT': 'What control algorithm was used in the actuation system intervention at the system level? Other',
'Q121': 'How was the occupant being asked to adapt in the space?',
'Q121_4_TEXT': 'How was the occupant being asked to adapt in the space? Other',
'Q85': 'What are the ways that behaviour change was driven?',
'Q85_4_TEXT': 'What are the ways that behaviour change was driven? Other',
'Q62_1': "Degree of occupant-centeredness. How was occupant data used to improve or optimise the control algorithm? Choose any that apply. * Responsive/adaptive control refers to control algorithms based on 'current state' data   Anticipatory/ predictive cotrol resers to control algorithms based on 'future stae' predictions - Occupant data or sensor data was used for responsive/ adaptive control as opposed to anticipatory control. Data used includes:",
'Q62_1_TEXT': "Degree of occupant-centeredness. How was occupant data used to improve or optimise the control algorithm? Choose any that apply. * Responsive/adaptive control refers to control algorithms based on 'current state' data   Anticipatory/ predictive cotrol resers to control algorithms based on 'future stae' predictions - Occupant data or sensor data was used for responsive/ adaptive control as opposed to anticipatory control. Data used includes: - Text",
'Q62_2': "Degree of occupant-centeredness. How was occupant data used to improve or optimise the control algorithm? Choose any that apply. * Responsive/adaptive control refers to control algorithms based on 'current state' data   Anticipatory/ predictive cotrol resers to control algorithms based on 'future stae' predictions - Occupant modelling was used for responsive/ adaptive control as opposed to anticipatory control. The modeling methods are based on:",
'Q62_3': "Degree of occupant-centeredness. How was occupant data used to improve or optimise the control algorithm? Choose any that apply. * Responsive/adaptive control refers to control algorithms based on 'current state' data   Anticipatory/ predictive cotrol resers to control algorithms based on 'future stae' predictions - Occupant modelling was used for anticipatory/ predictive control. The modeling methods are based on:",
'Q62_4': "Degree of occupant-centeredness. How was occupant data used to improve or optimise the control algorithm? Choose any that apply. * Responsive/adaptive control refers to control algorithms based on 'current state' data   Anticipatory/ predictive cotrol resers to control algorithms based on 'future stae' predictions - Feedback from the occupant e.g. surveys: app usage: occupant overrides were used to improve/ optimise building control via:",
'Q63': 'What was the objective of the occupant-centric operations intervention for the study?You may indicate more than one and a short series of questions will be activated for each that allows you to quantify the impact on that objective.',
'Q63_9_TEXT': 'What was the objective of the occupant-centric operations intervention for the study?You may indicate more than one and a short series of questions will be activated for each that allows you to quantify the impact on that objective. Other',
'Q92_1_1': 'Energy efficiencyPlease provide results from pre and post intervention data related to the variable AND/OR the verified difference between pre and post measurement. Please indicate the units. There is no need to fill out all three columns. - Energy saving power consumption total - Pre intervention data include unit',
'Q92_1_2': 'Energy efficiencyPlease provide results from pre and post intervention data related to the variable AND/OR the verified difference between pre and post measurement. Please indicate the units. There is no need to fill out all three columns. - Energy saving power consumption total - Post intervention data include unit',
'Q92_1_3': 'Energy efficiencyPlease provide results from pre and post intervention data related to the variable AND/OR the verified difference between pre and post measurement. Please indicate the units. There is no need to fill out all three columns. - Energy saving power consumption total - Difference between Pre and Post intervention data include unit',
'Q92_2_1': 'Energy efficiencyPlease provide results from pre and post intervention data related to the variable AND/OR the verified difference between pre and post measurement. Please indicate the units. There is no need to fill out all three columns. - Energy saving - electric - Pre intervention data include unit',
'Q92_2_2': 'Energy efficiencyPlease provide results from pre and post intervention data related to the variable AND/OR the verified difference between pre and post measurement. Please indicate the units. There is no need to fill out all three columns. - Energy saving - electric - Post intervention data include unit',
'Q92_2_3': 'Energy efficiencyPlease provide results from pre and post intervention data related to the variable AND/OR the verified difference between pre and post measurement. Please indicate the units. There is no need to fill out all three columns. - Energy saving - electric - Difference between Pre and Post intervention data include unit',
'Q92_3_1': 'Energy efficiencyPlease provide results from pre and post intervention data related to the variable AND/OR the verified difference between pre and post measurement. Please indicate the units. There is no need to fill out all three columns. - Energy saving - heating load - Pre intervention data include unit',
'Q92_3_2': 'Energy efficiencyPlease provide results from pre and post intervention data related to the variable AND/OR the verified difference between pre and post measurement. Please indicate the units. There is no need to fill out all three columns. - Energy saving - heating load - Post intervention data include unit',
'Q92_3_3': 'Energy efficiencyPlease provide results from pre and post intervention data related to the variable AND/OR the verified difference between pre and post measurement. Please indicate the units. There is no need to fill out all three columns. - Energy saving - heating load - Difference between Pre and Post intervention data include unit',
'Q92_4_1': 'Energy efficiencyPlease provide results from pre and post intervention data related to the variable AND/OR the verified difference between pre and post measurement. Please indicate the units. There is no need to fill out all three columns. - Energy saving - cooling load - Pre intervention data include unit',
'Q92_4_2': 'Energy efficiencyPlease provide results from pre and post intervention data related to the variable AND/OR the verified difference between pre and post measurement. Please indicate the units. There is no need to fill out all three columns. - Energy saving - cooling load - Post intervention data include unit',
'Q92_4_3': 'Energy efficiencyPlease provide results from pre and post intervention data related to the variable AND/OR the verified difference between pre and post measurement. Please indicate the units. There is no need to fill out all three columns. - Energy saving - cooling load - Difference between Pre and Post intervention data include unit',
'Q92_5_1': 'Energy efficiencyPlease provide results from pre and post intervention data related to the variable AND/OR the verified difference between pre and post measurement. Please indicate the units. There is no need to fill out all three columns. - Energy cost - Pre intervention data include unit',
'Q92_5_2': 'Energy efficiencyPlease provide results from pre and post intervention data related to the variable AND/OR the verified difference between pre and post measurement. Please indicate the units. There is no need to fill out all three columns. - Energy cost - Post intervention data include unit',
'Q92_5_3': 'Energy efficiencyPlease provide results from pre and post intervention data related to the variable AND/OR the verified difference between pre and post measurement. Please indicate the units. There is no need to fill out all three columns. - Energy cost - Difference between Pre and Post intervention data include unit',
'Q92_6_1': 'Energy efficiencyPlease provide results from pre and post intervention data related to the variable AND/OR the verified difference between pre and post measurement. Please indicate the units. There is no need to fill out all three columns. - Demand cost - Pre intervention data include unit',
'Q92_6_2': 'Energy efficiencyPlease provide results from pre and post intervention data related to the variable AND/OR the verified difference between pre and post measurement. Please indicate the units. There is no need to fill out all three columns. - Demand cost - Post intervention data include unit',
'Q92_6_3': 'Energy efficiencyPlease provide results from pre and post intervention data related to the variable AND/OR the verified difference between pre and post measurement. Please indicate the units. There is no need to fill out all three columns. - Demand cost - Difference between Pre and Post intervention data include unit',
'Q92_7_1': 'Energy efficiencyPlease provide results from pre and post intervention data related to the variable AND/OR the verified difference between pre and post measurement. Please indicate the units. There is no need to fill out all three columns. - Energy flexibilty - Pre intervention data include unit',
'Q92_7_2': 'Energy efficiencyPlease provide results from pre and post intervention data related to the variable AND/OR the verified difference between pre and post measurement. Please indicate the units. There is no need to fill out all three columns. - Energy flexibilty - Post intervention data include unit',
'Q92_7_3': 'Energy efficiencyPlease provide results from pre and post intervention data related to the variable AND/OR the verified difference between pre and post measurement. Please indicate the units. There is no need to fill out all three columns. - Energy flexibilty - Difference between Pre and Post intervention data include unit',
'Q92_8_TEXT': 'Energy efficiencyPlease provide results from pre and post intervention data related to the variable AND/OR the verified difference between pre and post measurement. Please indicate the units. There is no need to fill out all three columns. - Other - Text',
'Q92_8_1': 'Energy efficiencyPlease provide results from pre and post intervention data related to the variable AND/OR the verified difference between pre and post measurement. Please indicate the units. There is no need to fill out all three columns. - Other - Pre intervention data include unit',
'Q92_8_2': 'Energy efficiencyPlease provide results from pre and post intervention data related to the variable AND/OR the verified difference between pre and post measurement. Please indicate the units. There is no need to fill out all three columns. - Other - Post intervention data include unit',
'Q92_8_3': 'Energy efficiencyPlease provide results from pre and post intervention data related to the variable AND/OR the verified difference between pre and post measurement. Please indicate the units. There is no need to fill out all three columns. - Other - Difference between Pre and Post intervention data include unit',
'Q88_1_1': 'ComfortPlease provide results from pre and post intervention data related to the variable AND/OR the verified difference between pre and post measurement. Please indicate the units. There is no need to fill out all three columns. - Thermal comfort - Pre intervention data include unit',
'Q88_1_2': 'ComfortPlease provide results from pre and post intervention data related to the variable AND/OR the verified difference between pre and post measurement. Please indicate the units. There is no need to fill out all three columns. - Thermal comfort - Post intervention data include unit',
'Q88_1_3': 'ComfortPlease provide results from pre and post intervention data related to the variable AND/OR the verified difference between pre and post measurement. Please indicate the units. There is no need to fill out all three columns. - Thermal comfort - Difference between Pre and Post intervention data include unit',
'Q88_2_1': 'ComfortPlease provide results from pre and post intervention data related to the variable AND/OR the verified difference between pre and post measurement. Please indicate the units. There is no need to fill out all three columns. - Visual comfort - Pre intervention data include unit',
'Q88_2_2': 'ComfortPlease provide results from pre and post intervention data related to the variable AND/OR the verified difference between pre and post measurement. Please indicate the units. There is no need to fill out all three columns. - Visual comfort - Post intervention data include unit',
'Q88_2_3': 'ComfortPlease provide results from pre and post intervention data related to the variable AND/OR the verified difference between pre and post measurement. Please indicate the units. There is no need to fill out all three columns. - Visual comfort - Difference between Pre and Post intervention data include unit',
'Q88_3_1': 'ComfortPlease provide results from pre and post intervention data related to the variable AND/OR the verified difference between pre and post measurement. Please indicate the units. There is no need to fill out all three columns. - Acoustic comfort - Pre intervention data include unit',
'Q88_3_2': 'ComfortPlease provide results from pre and post intervention data related to the variable AND/OR the verified difference between pre and post measurement. Please indicate the units. There is no need to fill out all three columns. - Acoustic comfort - Post intervention data include unit',
'Q88_3_3': 'ComfortPlease provide results from pre and post intervention data related to the variable AND/OR the verified difference between pre and post measurement. Please indicate the units. There is no need to fill out all three columns. - Acoustic comfort - Difference between Pre and Post intervention data include unit',
'Q88_4_TEXT': 'ComfortPlease provide results from pre and post intervention data related to the variable AND/OR the verified difference between pre and post measurement. Please indicate the units. There is no need to fill out all three columns. - Other - Text',
'Q88_4_1': 'ComfortPlease provide results from pre and post intervention data related to the variable AND/OR the verified difference between pre and post measurement. Please indicate the units. There is no need to fill out all three columns. - Other - Pre intervention data include unit',
'Q88_4_2': 'ComfortPlease provide results from pre and post intervention data related to the variable AND/OR the verified difference between pre and post measurement. Please indicate the units. There is no need to fill out all three columns. - Other - Post intervention data include unit',
'Q88_4_3': 'ComfortPlease provide results from pre and post intervention data related to the variable AND/OR the verified difference between pre and post measurement. Please indicate the units. There is no need to fill out all three columns. - Other - Difference between Pre and Post intervention data include unit',
'Q89_1_1': 'ProductivityPlease provide results from pre and post intervention data related to the variable AND/OR the verified difference between pre and post measurement. Please indicate the units. There is no need to fill out all three columns. - Worker productivity - Pre intervention data include unit',
'Q89_1_2': 'ProductivityPlease provide results from pre and post intervention data related to the variable AND/OR the verified difference between pre and post measurement. Please indicate the units. There is no need to fill out all three columns. - Worker productivity - Post intervention data include unit',
'Q89_1_3': 'ProductivityPlease provide results from pre and post intervention data related to the variable AND/OR the verified difference between pre and post measurement. Please indicate the units. There is no need to fill out all three columns. - Worker productivity - Difference between Pre and Post intervention data include unit',
'Q89_2_1': 'ProductivityPlease provide results from pre and post intervention data related to the variable AND/OR the verified difference between pre and post measurement. Please indicate the units. There is no need to fill out all three columns. - Student performance - Pre intervention data include unit',
'Q89_2_2': 'ProductivityPlease provide results from pre and post intervention data related to the variable AND/OR the verified difference between pre and post measurement. Please indicate the units. There is no need to fill out all three columns. - Student performance - Post intervention data include unit',
'Q89_2_3': 'ProductivityPlease provide results from pre and post intervention data related to the variable AND/OR the verified difference between pre and post measurement. Please indicate the units. There is no need to fill out all three columns. - Student performance - Difference between Pre and Post intervention data include unit',
'Q89_3_1': 'ProductivityPlease provide results from pre and post intervention data related to the variable AND/OR the verified difference between pre and post measurement. Please indicate the units. There is no need to fill out all three columns. - Fatigue - Pre intervention data include unit',
'Q89_3_2': 'ProductivityPlease provide results from pre and post intervention data related to the variable AND/OR the verified difference between pre and post measurement. Please indicate the units. There is no need to fill out all three columns. - Fatigue - Post intervention data include unit',
'Q89_3_3': 'ProductivityPlease provide results from pre and post intervention data related to the variable AND/OR the verified difference between pre and post measurement. Please indicate the units. There is no need to fill out all three columns. - Fatigue - Difference between Pre and Post intervention data include unit',
'Q89_4_TEXT': 'ProductivityPlease provide results from pre and post intervention data related to the variable AND/OR the verified difference between pre and post measurement. Please indicate the units. There is no need to fill out all three columns. - Other - Text',
'Q89_4_1': 'ProductivityPlease provide results from pre and post intervention data related to the variable AND/OR the verified difference between pre and post measurement. Please indicate the units. There is no need to fill out all three columns. - Other - Pre intervention data include unit',
'Q89_4_2': 'ProductivityPlease provide results from pre and post intervention data related to the variable AND/OR the verified difference between pre and post measurement. Please indicate the units. There is no need to fill out all three columns. - Other - Post intervention data include unit',
'Q89_4_3': 'ProductivityPlease provide results from pre and post intervention data related to the variable AND/OR the verified difference between pre and post measurement. Please indicate the units. There is no need to fill out all three columns. - Other - Difference between Pre and Post intervention data include unit',
'Q227_1_1': 'Health Please provide results from pre and post intervention data related to the variable AND/OR the verified difference between pre and post measurement. Please indicate the units. There is no need to fill out all three columns. - Respiratory/Cardiovascular disease - Pre intervention data include unit',
'Q227_1_2': 'Health Please provide results from pre and post intervention data related to the variable AND/OR the verified difference between pre and post measurement. Please indicate the units. There is no need to fill out all three columns. - Respiratory/Cardiovascular disease - Post intervention data include unit',
'Q227_1_3': 'Health Please provide results from pre and post intervention data related to the variable AND/OR the verified difference between pre and post measurement. Please indicate the units. There is no need to fill out all three columns. - Respiratory/Cardiovascular disease - Difference between Pre and Post intervention data include unit',
'Q227_2_1': 'Health Please provide results from pre and post intervention data related to the variable AND/OR the verified difference between pre and post measurement. Please indicate the units. There is no need to fill out all three columns. - Metabolic function - Pre intervention data include unit',
'Q227_2_2': 'Health Please provide results from pre and post intervention data related to the variable AND/OR the verified difference between pre and post measurement. Please indicate the units. There is no need to fill out all three columns. - Metabolic function - Post intervention data include unit',
'Q227_2_3': 'Health Please provide results from pre and post intervention data related to the variable AND/OR the verified difference between pre and post measurement. Please indicate the units. There is no need to fill out all three columns. - Metabolic function - Difference between Pre and Post intervention data include unit',
'Q227_3_1': 'Health Please provide results from pre and post intervention data related to the variable AND/OR the verified difference between pre and post measurement. Please indicate the units. There is no need to fill out all three columns. - Reduction of Sick Building Syndrome Symptoms headache: eye: nose: throat i... - Reduction of Sick Building Syndrome Symptoms headache: eye: nose: throat irritation: allergic reactions: fatigue etc. - Pre intervention data include unit',
'Q227_3_2': 'Health Please provide results from pre and post intervention data related to the variable AND/OR the verified difference between pre and post measurement. Please indicate the units. There is no need to fill out all three columns. - Reduction of Sick Building Syndrome Symptoms headache: eye: nose: throat i... - Reduction of Sick Building Syndrome Symptoms headache: eye: nose: throat irritation: allergic reactions: fatigue etc. - Post intervention data include unit',
'Q227_3_3': 'Health Please provide results from pre and post intervention data related to the variable AND/OR the verified difference between pre and post measurement. Please indicate the units. There is no need to fill out all three columns. - Reduction of Sick Building Syndrome Symptoms headache: eye: nose: throat i... - Reduction of Sick Building Syndrome Symptoms headache: eye: nose: throat irritation: allergic reactions: fatigue etc. - Difference between Pre and Post intervention data include unit',
'Q227_4_1': 'Health Please provide results from pre and post intervention data related to the variable AND/OR the verified difference between pre and post measurement. Please indicate the units. There is no need to fill out all three columns. - Sleepiness - Pre intervention data include unit',
'Q227_4_2': 'Health Please provide results from pre and post intervention data related to the variable AND/OR the verified difference between pre and post measurement. Please indicate the units. There is no need to fill out all three columns. - Sleepiness - Post intervention data include unit',
'Q227_4_3': 'Health Please provide results from pre and post intervention data related to the variable AND/OR the verified difference between pre and post measurement. Please indicate the units. There is no need to fill out all three columns. - Sleepiness - Difference between Pre and Post intervention data include unit',
'Q227_5_TEXT': 'Health Please provide results from pre and post intervention data related to the variable AND/OR the verified difference between pre and post measurement. Please indicate the units. There is no need to fill out all three columns. - Other - Text',
'Q227_5_1': 'Health Please provide results from pre and post intervention data related to the variable AND/OR the verified difference between pre and post measurement. Please indicate the units. There is no need to fill out all three columns. - Other - Pre intervention data include unit',
'Q227_5_2': 'Health Please provide results from pre and post intervention data related to the variable AND/OR the verified difference between pre and post measurement. Please indicate the units. There is no need to fill out all three columns. - Other - Post intervention data include unit',
'Q227_5_3': 'Health Please provide results from pre and post intervention data related to the variable AND/OR the verified difference between pre and post measurement. Please indicate the units. There is no need to fill out all three columns. - Other - Difference between Pre and Post intervention data include unit',
'Q228_1_1': 'Indoor environmental qualityPlease provide results from pre and post intervention data related to the variable AND/OR the verified difference between pre and post measurement. Please indicate the units. There is no need to fill out all three columns. - Indoor air quality: - Pre intervention data include unit',
'Q228_1_5': 'Indoor environmental qualityPlease provide results from pre and post intervention data related to the variable AND/OR the verified difference between pre and post measurement. Please indicate the units. There is no need to fill out all three columns. - Indoor air quality: - Post intervention data include units',
'Q228_1_2': 'Indoor environmental qualityPlease provide results from pre and post intervention data related to the variable AND/OR the verified difference between pre and post measurement. Please indicate the units. There is no need to fill out all three columns. - Indoor air quality: - Difference between Pre and Post intervention data include unit',
'Q228_2_1': 'Indoor environmental qualityPlease provide results from pre and post intervention data related to the variable AND/OR the verified difference between pre and post measurement. Please indicate the units. There is no need to fill out all three columns. - Humidity: - Pre intervention data include unit',
'Q228_2_5': 'Indoor environmental qualityPlease provide results from pre and post intervention data related to the variable AND/OR the verified difference between pre and post measurement. Please indicate the units. There is no need to fill out all three columns. - Humidity: - Post intervention data include units',
'Q228_2_2': 'Indoor environmental qualityPlease provide results from pre and post intervention data related to the variable AND/OR the verified difference between pre and post measurement. Please indicate the units. There is no need to fill out all three columns. - Humidity: - Difference between Pre and Post intervention data include unit',
'Q228_3_1': 'Indoor environmental qualityPlease provide results from pre and post intervention data related to the variable AND/OR the verified difference between pre and post measurement. Please indicate the units. There is no need to fill out all three columns. - Hygiene: - Pre intervention data include unit',
'Q228_3_5': 'Indoor environmental qualityPlease provide results from pre and post intervention data related to the variable AND/OR the verified difference between pre and post measurement. Please indicate the units. There is no need to fill out all three columns. - Hygiene: - Post intervention data include units',
'Q228_3_2': 'Indoor environmental qualityPlease provide results from pre and post intervention data related to the variable AND/OR the verified difference between pre and post measurement. Please indicate the units. There is no need to fill out all three columns. - Hygiene: - Difference between Pre and Post intervention data include unit',
'Q228_4_1': 'Indoor environmental qualityPlease provide results from pre and post intervention data related to the variable AND/OR the verified difference between pre and post measurement. Please indicate the units. There is no need to fill out all three columns. - Micro-organism: - Pre intervention data include unit',
'Q228_4_5': 'Indoor environmental qualityPlease provide results from pre and post intervention data related to the variable AND/OR the verified difference between pre and post measurement. Please indicate the units. There is no need to fill out all three columns. - Micro-organism: - Post intervention data include units',
'Q228_4_2': 'Indoor environmental qualityPlease provide results from pre and post intervention data related to the variable AND/OR the verified difference between pre and post measurement. Please indicate the units. There is no need to fill out all three columns. - Micro-organism: - Difference between Pre and Post intervention data include unit',
'Q228_5_1': 'Indoor environmental qualityPlease provide results from pre and post intervention data related to the variable AND/OR the verified difference between pre and post measurement. Please indicate the units. There is no need to fill out all three columns. - Odor: - Pre intervention data include unit',
'Q228_5_5': 'Indoor environmental qualityPlease provide results from pre and post intervention data related to the variable AND/OR the verified difference between pre and post measurement. Please indicate the units. There is no need to fill out all three columns. - Odor: - Post intervention data include units',
'Q228_5_2': 'Indoor environmental qualityPlease provide results from pre and post intervention data related to the variable AND/OR the verified difference between pre and post measurement. Please indicate the units. There is no need to fill out all three columns. - Odor: - Difference between Pre and Post intervention data include unit',
'Q228_6_1': 'Indoor environmental qualityPlease provide results from pre and post intervention data related to the variable AND/OR the verified difference between pre and post measurement. Please indicate the units. There is no need to fill out all three columns. - Ergonomics: - Pre intervention data include unit',
'Q228_6_5': 'Indoor environmental qualityPlease provide results from pre and post intervention data related to the variable AND/OR the verified difference between pre and post measurement. Please indicate the units. There is no need to fill out all three columns. - Ergonomics: - Post intervention data include units',
'Q228_6_2': 'Indoor environmental qualityPlease provide results from pre and post intervention data related to the variable AND/OR the verified difference between pre and post measurement. Please indicate the units. There is no need to fill out all three columns. - Ergonomics: - Difference between Pre and Post intervention data include unit',
'Q228_7_1': 'Indoor environmental qualityPlease provide results from pre and post intervention data related to the variable AND/OR the verified difference between pre and post measurement. Please indicate the units. There is no need to fill out all three columns. - Electro-magnetic radiation: - Pre intervention data include unit',
'Q228_7_5': 'Indoor environmental qualityPlease provide results from pre and post intervention data related to the variable AND/OR the verified difference between pre and post measurement. Please indicate the units. There is no need to fill out all three columns. - Electro-magnetic radiation: - Post intervention data include units',
'Q228_7_2': 'Indoor environmental qualityPlease provide results from pre and post intervention data related to the variable AND/OR the verified difference between pre and post measurement. Please indicate the units. There is no need to fill out all three columns. - Electro-magnetic radiation: - Difference between Pre and Post intervention data include unit',
'Q228_8_1': 'Indoor environmental qualityPlease provide results from pre and post intervention data related to the variable AND/OR the verified difference between pre and post measurement. Please indicate the units. There is no need to fill out all three columns. - Sound quality: - Pre intervention data include unit',
'Q228_8_5': 'Indoor environmental qualityPlease provide results from pre and post intervention data related to the variable AND/OR the verified difference between pre and post measurement. Please indicate the units. There is no need to fill out all three columns. - Sound quality: - Post intervention data include units',
'Q228_8_2': 'Indoor environmental qualityPlease provide results from pre and post intervention data related to the variable AND/OR the verified difference between pre and post measurement. Please indicate the units. There is no need to fill out all three columns. - Sound quality: - Difference between Pre and Post intervention data include unit',
'Q228_9_1': 'Indoor environmental qualityPlease provide results from pre and post intervention data related to the variable AND/OR the verified difference between pre and post measurement. Please indicate the units. There is no need to fill out all three columns. - Vibration: - Pre intervention data include unit',
'Q228_9_5': 'Indoor environmental qualityPlease provide results from pre and post intervention data related to the variable AND/OR the verified difference between pre and post measurement. Please indicate the units. There is no need to fill out all three columns. - Vibration: - Post intervention data include units',
'Q228_9_2': 'Indoor environmental qualityPlease provide results from pre and post intervention data related to the variable AND/OR the verified difference between pre and post measurement. Please indicate the units. There is no need to fill out all three columns. - Vibration: - Difference between Pre and Post intervention data include unit',
'Q228_10_TEXT': 'Indoor environmental qualityPlease provide results from pre and post intervention data related to the variable AND/OR the verified difference between pre and post measurement. Please indicate the units. There is no need to fill out all three columns. - Other: - Text',
'Q228_10_1': 'Indoor environmental qualityPlease provide results from pre and post intervention data related to the variable AND/OR the verified difference between pre and post measurement. Please indicate the units. There is no need to fill out all three columns. - Other: - Pre intervention data include unit',
'Q228_10_5': 'Indoor environmental qualityPlease provide results from pre and post intervention data related to the variable AND/OR the verified difference between pre and post measurement. Please indicate the units. There is no need to fill out all three columns. - Other: - Post intervention data include units',
'Q228_10_2': 'Indoor environmental qualityPlease provide results from pre and post intervention data related to the variable AND/OR the verified difference between pre and post measurement. Please indicate the units. There is no need to fill out all three columns. - Other: - Difference between Pre and Post intervention data include unit',
'Q245_1': 'What was the objectives of the machine learning models in this study? - Thermal preference',
'Q245_2': 'What was the objectives of the machine learning models in this study? - Thermal sensation',
'Q245_3': 'What was the objectives of the machine learning models in this study? - Thermal satisfaction',
'Q245_4': 'What was the objectives of the machine learning models in this study? - Thermal sensitivity',
'Q245_5': 'What was the objectives of the machine learning models in this study? - Optimal thermal comfort setpoint',
'Q245_6': 'What was the objectives of the machine learning models in this study? - Optimal fan speed or operation',
'Q245_7': 'What was the objectives of the machine learning models in this study? - Noise preference/sensation',
'Q245_8': 'What was the objectives of the machine learning models in this study? - Lighting preference/sensation',
'Q245_9': 'What was the objectives of the machine learning models in this study? - Lighting status or setpoint',
'Q245_10': 'What was the objectives of the machine learning models in this study? - Door status',
'Q245_11': 'What was the objectives of the machine learning models in this study? - Window status',
'Q245_12': 'What was the objectives of the machine learning models in this study? - Appliance usage',
'Q245_13': 'What was the objectives of the machine learning models in this study? - Other',
'Q245_13_TEXT': 'What was the objectives of the machine learning models in this study? - Other - Text',
'Q245_14': 'What was the objectives of the machine learning models in this study? - Not applicable',
'Q245_15': "What was the objectives of the machine learning models in this study? - I don't know",
'Q251': 'What categories of machine learning model inputs were used?',
'Q251_5_TEXT': 'What categories of machine learning model inputs were used? Other',
'Q246': 'What was the number of datapoints used in the studies? i.e.: the total number of observations used for model training: validation and testing.',
'Q249_1': 'Select all machine learning models or methods that were used and whether they were used as a baseline or proposed model. You can indicate the models that performed the best in the far right column. - Fuzzy Classification',
'Q249_2': 'Select all machine learning models or methods that were used and whether they were used as a baseline or proposed model. You can indicate the models that performed the best in the far right column. - Random Forest',
'Q249_3': 'Select all machine learning models or methods that were used and whether they were used as a baseline or proposed model. You can indicate the models that performed the best in the far right column. - K-Nearest Neighbors',
'Q249_4': 'Select all machine learning models or methods that were used and whether they were used as a baseline or proposed model. You can indicate the models that performed the best in the far right column. - Support Vector Machines',
'Q249_5': 'Select all machine learning models or methods that were used and whether they were used as a baseline or proposed model. You can indicate the models that performed the best in the far right column. - Decision Tree',
'Q249_6': 'Select all machine learning models or methods that were used and whether they were used as a baseline or proposed model. You can indicate the models that performed the best in the far right column. - Linear Discriminant Analysis',
'Q249_7': 'Select all machine learning models or methods that were used and whether they were used as a baseline or proposed model. You can indicate the models that performed the best in the far right column. - Bayesian Inference/Classification',
'Q249_8': 'Select all machine learning models or methods that were used and whether they were used as a baseline or proposed model. You can indicate the models that performed the best in the far right column. - Multinomial Logistic Regression',
'Q249_9': 'Select all machine learning models or methods that were used and whether they were used as a baseline or proposed model. You can indicate the models that performed the best in the far right column. - Gradient Boosting Machines',
'Q249_10': 'Select all machine learning models or methods that were used and whether they were used as a baseline or proposed model. You can indicate the models that performed the best in the far right column. - Learning Vector Quantization',
'Q249_11': 'Select all machine learning models or methods that were used and whether they were used as a baseline or proposed model. You can indicate the models that performed the best in the far right column. - Ordered Probit',
'Q249_12': 'Select all machine learning models or methods that were used and whether they were used as a baseline or proposed model. You can indicate the models that performed the best in the far right column. - Linear Regression',
'Q249_13': 'Select all machine learning models or methods that were used and whether they were used as a baseline or proposed model. You can indicate the models that performed the best in the far right column. - Naive Bayes',
'Q249_14': 'Select all machine learning models or methods that were used and whether they were used as a baseline or proposed model. You can indicate the models that performed the best in the far right column. - Rule-based Classifer',
'Q249_15': 'Select all machine learning models or methods that were used and whether they were used as a baseline or proposed model. You can indicate the models that performed the best in the far right column. - Classification and Regression Trees',
'Q249_16': 'Select all machine learning models or methods that were used and whether they were used as a baseline or proposed model. You can indicate the models that performed the best in the far right column. - Artificial Neural Networks',
'Q249_17': 'Select all machine learning models or methods that were used and whether they were used as a baseline or proposed model. You can indicate the models that performed the best in the far right column. - Convolutional Neural Networks',
'Q249_18': 'Select all machine learning models or methods that were used and whether they were used as a baseline or proposed model. You can indicate the models that performed the best in the far right column. - Recurrent Neural Networks',
'Q249_19': 'Select all machine learning models or methods that were used and whether they were used as a baseline or proposed model. You can indicate the models that performed the best in the far right column. - Other',
'Q249_19_TEXT': 'Select all machine learning models or methods that were used and whether they were used as a baseline or proposed model. You can indicate the models that performed the best in the far right column. Other',
'Q249_20': "Select all machine learning models or methods that were used and whether they were used as a baseline or proposed model. You can indicate the models that performed the best in the far right column. - I don't know",
'Q249_21': 'Select all machine learning models or methods that were used and whether they were used as a baseline or proposed model. You can indicate the models that performed the best in the far right column. - Not applicable',
'Q252': 'What tools/languages were used to create the machine learning model/process?',
'Q252_5_TEXT': 'What tools/languages were used to create the machine learning model/process? Other',
'Q250': 'If possible: describe in 2-3 sentences the baseline versus proposed model strategy and by what percentage or magnitude the proposed methods were better or worse than the baseline.',
'Q253': 'Did you create a method for reproducibility of your modelling process using an open source respository i.e.: Zenodo: Github: etc.?',
'Q253_6_TEXT': 'Did you create a method for reproducibility of your modelling process using an open source respository i.e.: Zenodo: Github: etc.? Other',
'Q254': 'If you have shared your data/code online: please provide a link to the repository/data source.',
'Q194': "Is there anything else you would like to share about your case study that hasn't been covered in previous questions? data categories: intervention types: etc",
'Country_Cleaned_Up': 'Country_Cleaned_Up',
'Test-Response': 'Test-Response',
}